# Generated by Django 2.2.17 on 2021-03-23 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='users_chosen',
            field=models.ManyToManyField(related_name='chosen_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
