# Generated by Django 2.2.17 on 2021-03-23 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_users_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='users_chosen',
            field=models.ManyToManyField(null=True, related_name='chosen_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
