# Generated by Django 3.2.10 on 2021-12-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_question_time_limit_mins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchoice',
            options={'ordering': ('candidate', 'test_question__id')},
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
