# Generated by Django 2.2.17 on 2021-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_submission_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
