# Generated by Django 2.2.17 on 2021-03-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210323_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit_mins',
            field=models.IntegerField(blank=True),
        ),
    ]
